# Example docker compose
version: '3.7'

services:
  litecoin:
    build: .
    container_name: litecoin-node
    volumes:
      - ./litecoindata:/home/litecoin/.litecoin
    ports:
      - "9333:9333"
    restart: always
    environment:
      - LITECOIN_MAXCONNECTIONS=50
      - LITECOIN_RPCUSER=yourusername
      - LITECOIN_RPCPASSWORD=yourpassword
